name: asr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  cupertino_icons: ^1.0.8
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  path_provider: ^2.1.1
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  share_plus: ^13.3.0
  shared_preferences: ^2.3.2
  audioplayers: ^6.0.0
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.0
  purchases_flutter: ^8.6.0
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:


  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/sounds/
    - assets/translations/
